### ISSUE TITLE
rtail

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/team-review#13]
https://gratipay.com/rtail/

cc: @kilianc

**Comment by kilianc** [comment]
Thanks @whit537

**Comment by chadwhitacre** [comment]
@kilianc No problem, thanks for applying. :-) You mind if we link to https://github.com/kilianc/rtail from the "How to get involved" section?

**Comment by kilianc** [comment]
@whit537 sure, I don't mind, I don't know the context but it should be fine, just send me the link when it's done :+1:

**Comment by chadwhitacre** [comment]
Sorry ... context is https://gratipay.com/rtail/. I've updated it with the Github link. The rest looks okay to me, so I've gone ahead and accepted your application. Welcome aboard! :-)

Watch our [blog](https://medium.com/gratipay-blog) for ~monthly updates, and check [the Radar](https://github.com/gratipay/inside.gratipay.com/labels/Radar) when you want to see our week-to-week priorities. Current status is: lots of cleanup following a big shakedown a month or two ago, getting ready to [flush "1.0 money" out of the system](https://github.com/gratipay/gratipay.com/issues/3539). If you hit any snags, let us now on [public GitHub](https://github.com/gratipay/gratipay.com/issues/new) or [private email](mailto:support@gratipay.com) and we'll see what we can do. :-)
