### ISSUE TITLE
Northern Plains Athletics

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#131]
This team was in the original batch at https://github.com/gratipay/inside.gratipay.com/issues/234.

(btw, this is my team)

**Comment by mattbk** [comment]
Onboarding can be updated to http://northernplainsathletics.com/about.

**Comment by webmaven** [comment]
Todo can be updated to https://github.com/mattbk/npa/issues

**Comment by chadwhitacre** [comment]
Done, thanks @mattbk @webmaven! :)
