### ISSUE TITLE
davorg

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/team-review#14]
https://gratipay.com/davorg/

cc: @davorg

**Comment by chadwhitacre** [comment]
Thanks for the application, @davorg. Can we figure something out for the "revenue model" section? You could [review current teams](https://gratipay.com/explore/teams/) for inspiration, but note that the first dozen are so have no revenue model stated due to a bug. :-(

The essence of the question is: how do/will you prompt your users to support your team's work? P.S. I've made a PR to use this language on the team application: https://github.com/gratipay/gratipay.com/pull/3621.

**Comment by chadwhitacre** [comment]
Empty revenue model bug, ftr: https://github.com/gratipay/gratipay.com/issues/3482.

**Comment by davorg** [comment]
Ok. Here's some text for the revenue model -

This is a one-person team and costs are minimal. My consulting company donates web hosting and I work on the modules in my spare time. If I started to get donations, I'd be surprised if I ever got a surplus over the hosting costs.

Does that look ok?

**Comment by chadwhitacre** [comment]
Well, that talks about _costs_, but what we're looking for here is _income_. Setting up a Gratipay account isn't instant money. What's your plan for getting people to actually donate to you through Gratipay? Do you have a Twitter following? Do you announce new releases via email? How do you communicate with your users/customers? What opportunities do you have to prompt them to support your work?

**Comment by chadwhitacre** [comment]
Since you're a Perl monger you might want to take a similar tack to https://gratipay.com/cpan-book/?

**Comment by davorg** [comment]
If I was being truthful, it would say something like this:

"I don't do this for the money and don't ask people to support me. Any donations I receive through Gratipay are a complete surprise (but much appreciated)."

Really, I'm just doing this in order to extract the money that kind people have already donated to me. If no-one ever donated a cent more then it wouldn't worry me at all.

**Comment by chadwhitacre** [comment]
@davorg Would it make more sense to whitelist your ~davorg user account for a one-time payout and call it a day? That's an option if you'd prefer.

**Comment by davorg** [comment]
Well, if at all possible I'd like it if the few people who were giving me money on Gratipay could continue to do so if they want to. So, paraphrasing BOOK's revenue model could we say something like:

"We receive donations from people who found our modules useful."

**Comment by chadwhitacre** [comment]
@davorg Sure thing. I've updated the "revenue model" section. Can we link to your GitHub in the "getting involved" section? Is https://github.com/davorg the best link to use?

**Comment by davorg** [comment]
Yeah, that would be fine.
And thanks for the PayPal payment 
On 16 Jul 2015 21:59, Chad Whitacre notifications@github.com wrote:@davorg Sure thing. I've updated the "revenue model" section. Can we link to your GitHub in "getting involved" section? Is https://github.com/davorg the best link to use?

**Comment by chadwhitacre** [comment]
Okay, all set! Welcome aboard! :-)

https://gratipay.com/davorg/
