### ISSUE TITLE
svg.js

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#15]
https://gratipay.com/svg-js/

**Comment by chadwhitacre** [comment]
Thanks for the Gratipay Team application, @wout! Reviewing it here ...

https://gratipay.com/svg-js/

For "How to get involved" may I add a link to https://github.com/wout/svg.js?

You answered the "Revenue Model" question in an interesting way. I'm not sure what to do with it. I see how you could interpret the prompt that way, but we were more looking for answers like on https://gratipay.com/endless-parentheses/.

**Comment by mattbk** [comment]
Perhaps an email to @wout would get his attention?  It looks like he hasn't been on GitHub for at least a month.

**Comment by chadwhitacre** [comment]
Called it good. Over on https://github.com/gratipay/gratipay.com/issues/3677 it sounds like the revenue model question is going to be significantly rewritten anyway.
