### ISSUE TITLE
Endless Parentheses

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#16]
https://gratipay.com/endless-parentheses/

**Comment by chadwhitacre** [comment]
Ping @Malabarba. Thanks for your Gratipay Team application! Reviewing it here ...

https://gratipay.com/endless-parentheses/

Looks good in general. Can we work on the "How Revenue is Shared" section? How will/would you share revenue if/when you have more contributors?

**Comment by Malabarba** [comment]
> How will/would you share revenue if/when you have more contributors?

Once the cost of the blog (which is pretty low) has been accounted for, I'll divide revenue evenly between all team members. 

If anyone presents frequent contributions and is interested in helping maintain the projects, I'll be happy to add make them as permanent team members and share the revenue.

**Comment by chadwhitacre** [comment]
Cool. I've added that to your page and have approved your account. Welcome aboard! :-)

**Comment by Malabarba** [comment]
Awesome! Thanks you.
