### ISSUE TITLE
README.md does not explain how to approve/decline applications

### ISSUE THREAD

**Issue by techtonik** [gratipay/team-review#170]
I don't see how can I deny this application https://github.com/gratipay/team-review/issues/169

**Comment by mattbk** [comment]
![image](https://cloud.githubusercontent.com/assets/3729038/13303762/be02502a-db16-11e5-97b1-67d95daaeba5.png)

**Comment by techtonik** [comment]
The screenshot is almost good to be included in README.md, except that it could be more positive and based on something people would be able to find live.

**Comment by chadwhitacre** [comment]
I would actually expect this to show up on "Review Teams" since the audience for this content is internal ("Inside Gratipay") as opposed to external (Team applicants).

**Comment by whit537** [comment]
inside.gratipay.com/howto/review-teams

**Comment by chadwhitacre** [comment]
http://inside.gratipay.com/howto/review-teams

**Comment by chadwhitacre** [comment]
Yeah, let's please reticket this in IG. Or, better yet, make a PR to update the relevant doc. :-)
