### ISSUE TITLE
trakt for Plex

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#18]
https://gratipay.com/trakt-for-plex/

**Comment by chadwhitacre** [comment]
Ping @fuzeman. Thanks for your Gratipay Team application! Reviewing it here ...

https://gratipay.com/trakt-for-plex/

**Comment by chadwhitacre** [comment]
@fuzeman TBH, I'm sniffing the air for copyright infringement (reminds me on first impression of fansubbing, cf. https://github.com/gratipay/inside.gratipay.com/issues/210#issuecomment-106471300 and https://github.com/gratipay/gratipay.com/pull/3568#issuecomment-123759865). The fact that you're under the `trakt` org makes it look like you're more legit. You're also in the Python community and a Gratipay member for three years, back from the ol' Git Tip days. :-)

**Comment by chadwhitacre** [comment]
> Scrobbling a song means that when you listen to it, the name of the song is sent to Last.fm and added to your music profile. 

http://www.last.fm/help/faq?category=99

**Comment by chadwhitacre** [comment]
> Plex is a suite of software and services that makes it easy for you to organize, enjoy and share your digital media, and access it from all your devices.

https://twitter.com/plexapp

> Trakt.tv is a platform that does many things, but primarily keeps track of TV shows and movies you watch. It integrates with your media center or home theater PC to enable scrobbling, so everything is automatic.

http://trakt.tv/about

> scrobble all media playing on your server to your trakt.tv account

https://github.com/trakt/Plex-Trakt-Scrobbler

> Scrobbling a ~~song~~ _video_ means that when you ~~listen to~~ _watch_ it, the name of the ~~song~~ _video_ is sent to ~~Last.fm~~ _Trakt.tv_ and added to your ~~music~~ profile.

Okay! [TIL](https://xkcd.com/1053/). :-)

Application approved. Welcome aboard Gratipay 2.0, @fuzeman! :dancer:

**Comment by fuzeman** [comment]
Thanks, glad to be back on Gratipay :smile:
