### ISSUE TITLE
Record cutting needles

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#27]
https://gratipay.com/record-cutting-needles/

**Comment by chadwhitacre** [comment]
This one is kinda fun, but it's not ready for prime time yet.

**Comment by chadwhitacre** [comment]
@mattbk Could you email the owner of this account to bring them into this conversation?

**Comment by mattbk** [comment]
Done.

**Comment by chadwhitacre** [comment]
Awesome, thanks. :-)

**Comment by mattbk** [comment]
Response below from https://gratipay.freshdesk.com/helpdesk/tickets/2717.

---

Thanks for taking the time in giving me the opportunity to join Gratipay. I am old school so to speak, and do not have a website for my product. Hopefully in the future that may be a possibility.
My team name...what about The Needle Man.
my product or service?
For nearly two years I have sold record cutting needles on ebay. These tiny triangle and cone shaped needles are used in many vintage home record cutting machines like Wilcox-Gay Recordettes, Recordios. They are also used in Rek-o-Kut, Presto, and other machines as well. I hand tool each needle that I sell. On my steel needles I have sold more than 440, and my other newer listing on ebay for needles in tungsten steel  are selling as well.
As far as I know only a couple more people in the world sell these needles (especially the cones as the triangles are harder to make). There are many people in the world that love record cutting; in lacquer, polycarbonate, and even plastic pie plates. There is a special website, lathetrolls.com where lathe cutting enthusiasts gather and trade information regularly.
 I need help with my tiny company for newer equipment, where I can continue to provide my products and to continue to improve my needle making process.
My ebay listings are as follows (just copy and paste the numbers  in the search on ebay):

 281255271864
 281686909853
Here you will find my listings. I agree with your terms of service.
Thanks Matt,

Jerry []

**Comment by chadwhitacre** [comment]
http://www.ebay.com/itm/281255271864
http://www.ebay.com/itm/281686909853

**Comment by chadwhitacre** [comment]
I mean, this is awesome, and Jerry seems like a neat guy, but he's pretty clearly not offering open work. Right?

**Comment by chadwhitacre** [comment]
I think we need to reject this application, because he's not offering open work. Objections?

**Comment by mattbk** [comment]
I do not object.

**Comment by chadwhitacre** [comment]
Ftr, @mattbk's response was:

> I'm sorry to tell you this, but we cannot accept your application for a Gratipay Team because you're not offering open work (https://gratipay.com/about/).  Discussion about this was at https://github.com/gratipay/team-review/issues/27.
> 
> Thanks for the interest,

**Comment by chadwhitacre** [comment]
!m @mattbk

**Comment by chadwhitacre** [comment]
@mattbk May I leave you the honor of updating the Team's status? :-)

https://gratipay.com/record-cutting-needles/

**Comment by mattbk** [comment]
Knew I forgot something.
