### ISSUE TITLE
Magit

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#28]
https://gratipay.com/magit/

@tarsius, we're reviewing your team application here.

**Comment by mattbk** [comment]
This application looks solid and I would vote for approval.

@tarsius, I just saw the note at the bottom of your application.  I can authorize a payout to PayPal if you would like.

**Comment by tarsius** [comment]
@mattbk Yes, please do that.

**Comment by mattbk** [comment]
@tarsius, you're cleared for payout on Thursday.  With Gratipay 2.0, the goal is to hold as little money in escrow as possible, so when your team is approved, you'll receive payouts weekly.  

For the record (because this has confused others), no payments to your account have occurred while you've been in limbo, and no money has been transferred out of your previous supporters' accounts.

**Comment by chadwhitacre** [comment]
Looks good to me. Welcome aboard Gratipay 2.0, @tarsius! :-)

**Comment by tarsius** [comment]
I cannot find this payout inside PayPal. According to https://gratipay.com/~tarsius/history/ it happened on August 14, 2015. Could you please check on your side. Thanks.

**Comment by tarsius** [comment]
I would actually prefer a bank transfer if that is possible.

**Comment by whit537** [comment]
> I cannot find this payout inside PayPal. According to https://gratipay.com/~tarsius/history/ it happened on August 14, 2015. Could you please check on your side. Thanks.

@tarsius Hmm ... not sure what's going on here. I do find the transaction "completed" in our PayPal history.

... I just called PayPal, and they said that you should call them. Sounds like there might be an additional step you need to take on your end, though of course they couldn't discuss your account details with me. :-)

> I would actually prefer a bank transfer if that is possible.

If you're in the U.S. then watch https://github.com/gratipay/gratipay.com/issues/726, if not then watch https://github.com/gratipay/gratipay.com/issues/417.

**Comment by tarsius** [comment]
The problem has been resolved. In the end it was me who messed up. Sorry for the noise.

When you see this could you please delete all messages concerning the transaction issue from this github issue. Thanks.

**Comment by whit537** [comment]
@tarsius Cool, and will do. In the future feel free to email support@gratipay.com for private support.

**Comment by tarsius** [comment]
Besides the new `magit` team there's also the old frankenteam `~magit`. Can I safely delete `~magit` now? I have downloaded the old history by copying it from https://gratipay.com/~magit/history/?year=2015 and 2014. Is there a better way?

**Comment by chadwhitacre** [comment]
@tarsius Do you know if we migrated the tips that `~magit` was receiving to the `magit` team? If not then maybe we should?

Also, we do have an export API around here somewhere ... 

Try [this](https://gratipay.com/~magit/history/export). Here's [the code for it](https://github.com/gratipay/gratipay.com/blob/1913/www/~/%25username/history/export.spt) if you want to see what you can get out of it. Sorry we don't have it documented. :-(
