### ISSUE TITLE
Nim programming language

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#29]
https://gratipay.com/nim-programming-language/

@dom96, we're reviewing your team application here.

**Comment by mattbk** [comment]
I think this is a good application and I would vote for approval.

**Comment by dom96** [comment]
Thanks! Any chance we could merge some of the other Nim maintainers who get tips into this team? Specifically @araq who is also in the old nimrod team on gratipay.

**Comment by chadwhitacre** [comment]
Application approved. Welcome aboard Gratipay 2.0, @dom96! :-)

@rohitpaulk Do you remember where you migrated a second users' tips to a team? /me goes digging for it ...

**Comment by chadwhitacre** [comment]
@dom96 Actually, can we change the title of the team to just "Nim"?

**Comment by dom96** [comment]
@whit537 sure, thanks!

**Comment by chadwhitacre** [comment]
> sure, thanks!

Cool, thanks. Done! :-)

https://gratipay.com/nim/

**Comment by chadwhitacre** [comment]
> Do you remember where you migrated a second users' tips to a team?

I know it was for Kivy, but I'm not finding a record of it. Here are the Freshdesk tickets (login required) that are close to when we did that:

https://gratipay.freshdesk.com/helpdesk/tickets/2184
https://gratipay.freshdesk.com/helpdesk/tickets/2185

I'm not sure exactly how we did it though, I think you made it happen @rohitpaulk.

I guess we could switch the owner of the team, run migrate-tips, and then switch the owner back.

**Comment by chadwhitacre** [comment]
Looking at Gratipay balances and history, as well as [the GitHub contributors graph](https://github.com/nim-lang/Nim/graphs/contributors), it looks like @araq is the primary author of Nim, yes? Should payouts go to @dom96 or @araq?

**Comment by chadwhitacre** [comment]
@araq I'm going to wait to hear from you before migrating your tips over from [~Araq](https://gratipay.com/~Araq/) to [Nim](https://gratipay.com/Nim/). We should also pay you out your balance, which will require you linking a PayPal account. Since @dom96 appears to be legitimately involved in Nim I'll proceed with today's payday with him receiving Nim's payout.

**Comment by Araq** [comment]
I didn't link a PayPal account? ok, will fix this asap.

But yes, please send it on to dom96.

**Comment by rohitpaulk** [comment]
Hey @whit537 - It was for c-geek/ucoin, here's the issue - https://github.com/gratipay/inside.gratipay.com/issues/278

We didn't actually migrate a second user's tips though - I changed the owner, deleted the old owners tips, and migrated tips for the new owner. In this case, we'll need to run a manual SQL query to bypass [the clause that checks for migrated tips](https://github.com/gratipay/gratipay.com/blob/master/gratipay/models/team.py#L90-L101). 

I'm assigning this to myself, and I'll wait for you to signal green before I proceed.

**Comment by chadwhitacre** [comment]
Awesome, go for it, @rohitpaulk! :-)

Be sure to switch the owner back, since @araq hasn't linked a PayPal yet.

**Comment by rohitpaulk** [comment]
Done!

``` sql
WITH rows AS (
            INSERT INTO payment_instructions
                        (ctime, mtime, participant, team, amount, is_funded)
                 SELECT ct.ctime
                      , ct.mtime
                      , ct.tipper
                      , 'nim'
                      , ct.amount
                      , ct.is_funded
                   FROM current_tips ct
                   JOIN participants p ON p.username = tipper
                  WHERE ct.tippee='Araq'
                    AND p.claimed_time IS NOT NULL
                    AND p.is_suspicious IS NOT TRUE
                    AND p.is_closed IS NOT TRUE
              RETURNING 1
) SELECT count(*) FROM rows; #=> 11
```

**Comment by rohitpaulk** [comment]
Guess this is ready to be closed?

**Comment by chadwhitacre** [comment]
Awesome, thanks @rohitpaulk. Yeah, I think we're good to close this now.

Welcome aboard Gratipay 2.0, @Araq @dom96! :-)

**Comment by dom96** [comment]
Thank you!

**Comment by Araq** [comment]
Ping, I did add my paypal account information. Not sure why you already closed this issue?

**Comment by chadwhitacre** [comment]
Sorry @Araq, reopened. What are the action items left to close this ticket, from your point of view?

**Comment by chadwhitacre** [comment]
@Araq I've cleared you for a payout of your current Gratipay balance. You should see that this Thursday.

Who should receive the money for the [Nim](https://gratipay.com/nim/) team in the future? Should that be @dom96 or @Araq?

**Comment by Araq** [comment]
Ok, looking forward to the payout thanks. In the future @dom96 should receive the money.

**Comment by chadwhitacre** [comment]
Okay. @dom96 is all set to receive the funds from Nim. How about we leave this open through this Thursday's payment cycle to ensure you receive your payout successfully, @Araq. Sound good?

**Comment by Araq** [comment]
Great, thanks.

**Comment by Araq** [comment]
Ok, got the money. ;-)

**Comment by chadwhitacre** [comment]
Excellent! :)
