### ISSUE TITLE
image-optim

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/team-review#3]
https://gratipay.com/image-optim/

cc: @toy

**Comment by chadwhitacre** [comment]
I'm not seeing a revenue model. What can we put there instead of `...`? Who will pay image-optim, and for what? Presumably your revenue model is donations from your users, yes?

**Comment by toy** [comment]
Nagging a bit — while checking what is written in revenue model, I've noticed that it is empty for [Gratipay](https://gratipay.com/Gratipay/).

I'm not sure what to say about revenue model for `image_optim` as I'm not hoping for revenue or profit, more for encouragement. So it is either nonprofit or donations/donationware.

**Comment by chadwhitacre** [comment]
> while checking what is written in revenue model, I've noticed that it is empty for Gratipay.

@toy Good find! :-) All of the first teams have an empty revenue model due to [a bug](https://github.com/gratipay/gratipay.com/issues/3482). :-(

That said, it is _especially_ bad for Gratipay to have such a sparse Team page. Therefore, I've manually updated the info on https://gratipay.com/Gratipay/.

**Comment by chadwhitacre** [comment]
@toy I've approved https://gratipay.com/image-optim/ after adding the following text for revenue model:

> I'm not hoping for revenue or profit, more for encouragement. So it is either nonprofit or donations/donationware.

You okay with that?

**Comment by toy** [comment]
@whit537 Thanks! Yes the revenue model like this will be the most precise I can get.

**Comment by chadwhitacre** [comment]
Cool, thanks. Welcome aboard, and thanks for using Gratipay! :-)
