### ISSUE TITLE
Drypot

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#33]
https://gratipay.com/drypot/

@drypot, your team application is being reviewed here.

**Comment by chadwhitacre** [comment]
Gonna need some work on this team application, @drypot. What's your vision for rapixel.com? Do you _want_ it to succeed? What does success look like for Rapixel?

**Comment by drypot** [comment]
Rapixel is almost finished. :)

I know it looks primitive, but it’s finished.

Rapixel powers three sites with same code.

https://rapixel.com
https://osoky.com
https://drypot.com

I like simple variants. :)

I was received money from small group of friends before teams 2.0.

**Comment by chadwhitacre** [comment]
I like your sites! :-)

Is that your art on https://drypot.com/? I love it. :-)

Let's find a good way to express what you're about on your Gratipay Team page. Does it make sense to name the team "Rapixel" instead of "Drypot"? It sounds like Rapixel is the product you're looking to fund here, yes?

**Comment by drypot** [comment]
Drypot is correct as team name.

I maintain Rapixel and Sleek (BBS Code).

I receive money from Rapixel friends and Sleek friends together.

And currently converting some other product (RaySoda) as open source.

So, it will be good not to connect team name to product name.

I know what’s teams 2.0, but it’s not perfectly fit to my case, now.

I’m making small toys alone.

**Comment by chadwhitacre** [comment]
> I know what’s teams 2.0, but it’s not perfectly fit to my case, now.
> 
> I’m making small toys alone.

Hmm ... yeah, it sounds like we might not be a good fit for each other. :-(

The problem I see is that all the teams on Gratipay 2.0 need to be offering "open work." There needs to be an expectation that if I show up on https://github.com/drypot/rapixel or https://github.com/drypot/sleek or https://github.com/drypot/raysoda, I can orient myself and start making PRs without having to necessarily coordinate with you first, _and_ that this will start to create an obligation for you to share the Drypot team's revenue with me (assuming my PRs are good).

It's okay to have a team of one, but teams need to be open to growth. Are you open to growth for the Drypot team?

**Comment by drypot** [comment]
Thank you for your careful concern.

But It’s a little complex to me. ^^;

I give up. ^^;

Thank you.

Sorry for my poor english. ^^;

**Comment by chadwhitacre** [comment]
Sorry @drypot. :-(

Best wishes! :-)
