### ISSUE TITLE
coala

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#36]
https://gratipay.com/coala/

@sils1297, we are reviewing your team application here.

**Comment by sils** [comment]
@mattbk thanks, I'm available for any questions you might have.

**Comment by chadwhitacre** [comment]
Looks good to me. Welcome aboard Gratipay 2.0, @sils1297! :-)

**Comment by sils** [comment]
Many thanks, any hints on how we can promote that a bit better? I added a
donation hook to our new landing page at coala-analyzer.org for now. I
don't have a stable internet connection so can't search for duplicate bugs
or open one bug I'd suggest a bit of more elaborate documentation on
creating a team prominently linked from your webpage :)

We appreciate your service and will definitely consider paying something
back (money, code...) to you on long term!

2015-08-20 23:12 GMT+02:00 Chad Whitacre notifications@github.com:

**Comment by chadwhitacre** [comment]
> Many thanks, any hints on how we can promote that a bit better?

Check out http://tractionbook.com/! :-)

**Comment by sils** [comment]
Hi, I see there is no way to alter teams manually, if I need changes, do I request them here? Is changing the banner on top possible?

**Comment by chadwhitacre** [comment]
@sils1297 We have tickets for [making Teams editable](gratipay/gratipay.com#3545) and [adding an image for Teams](gratipay/gratipay.com#3701). We haven't talked yet about opening up the top banner image to editing (whether on Team or ~user profiles). We do have a ticket about [replacing the global banner with something less obtrusive](https://github.com/gratipay/gratipay.com/issues/3755). Let's pick up the banner discussion there.

**Comment by sils** [comment]
Hi, can you update the To-Do link for coala to point to https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Acoala-analyzer, as this covers the issues of our whole organization (plugins, gui, artwork, ...), not only the core repo.

**Comment by chadwhitacre** [comment]
@sils1297 Over at https://github.com/gratipay/gratipay.com/issues/3748 we discovered that the `/issues` endpoint is for authenticated users only, and is actually 404 when not logged in to GitHub. Would you like to use this instead?

https://github.com/search?q=is%3Aopen+user%3Acoala-analyzer&type=Issues

**Comment by sils** [comment]
Awesome, good!

2015-09-09 13:20 GMT+02:00 Chad Whitacre notifications@github.com:

**Comment by chadwhitacre** [comment]
Done! :-)

https://gratipay.com/coala/

**Comment by sils** [comment]
Hi, can you replace our logo with the following?

![coala](https://cloud.githubusercontent.com/assets/5716520/12170085/6be78344-b53e-11e5-892d-96c776ed0553.png)

**Comment by sils** [comment]
@whit537 ^

**Comment by chadwhitacre** [comment]
Ah, sorry ... thanks for the reminder. Reopening so I don't forget again. :)

**Comment by sils** [comment]
No problem, I know how things can get lost :)

**Comment by chadwhitacre** [comment]
Should be all set, @sils1297. :)

**Comment by chadwhitacre** [comment]
https://gratipay.com/coala/

**Comment by mattbk** [comment]
@sils1297, you can now edit your team info on the team page if you need to in the future.

**Comment by sils** [comment]
thanks! I already did that actually :)

**Comment by mattbk** [comment]
Awesome! Glad it works.

**Comment by sils** [comment]
Yes it is awesome indeed :)

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-07 18:04 GMT+01:00 mattbk notifications@github.com:
