### ISSUE TITLE
MD for Bootstrap

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#37]
https://gratipay.com/md-for-bootstrap/

@fezvrasta, your application is being reviewed here.

**Comment by chadwhitacre** [comment]
Looks pretty good, @fezvrasta, I've approved your Team. :-)

May I update the product description to be more ... descriptive? I propose we use this paragraph from the README:

> This Bootstrap theme is an easy way to use the new [Material Design guidelines by Google](http://www.google.com/design/spec/material-design/introduction.html) in your Bootstrap 3 based application.

Would that be alright with you?

**Comment by chadwhitacre** [comment]
Curren description for comparison:

> Material Design web stuff (CSS, HTML, JS)

**Comment by FezVrasta** [comment]
ok

**Comment by chadwhitacre** [comment]
Thanks @FezVrasta. Done! :-)

https://gratipay.com/md-for-bootstrap/

**Comment by FezVrasta** [comment]
Thanks! I should replace the old link (https://gratipay.com/~FezVrasta/) with the new one right?

**Comment by chadwhitacre** [comment]
@FezVrasta Yes! :-)
