### ISSUE TITLE
Concrete Clouds

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#43]
https://gratipay.com/concrete-clouds/

@ganwell, your team application is being reviewed here.

**Comment by ghost** [comment]
@mattbk Thanks. I extended the homepage a bit. I first wanted to do public relations later, when I have implemented the first layer, but my decision to create a team means to write a bit more about my goals.

**Comment by chadwhitacre** [comment]
Good enough, @ganwell. Thanks for joining Gratipay! :-)
