### ISSUE TITLE
Org-mode

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#44]
https://gratipay.com/org-mode/

@bzg, you know the drill.

**Comment by bzg** [comment]
mattbk notifications@github.com writes:

> https://gratipay.com/org-mode/
> 
> @bzg, you know the drill.

Yes, thanks.  If there is anything I can do to make it better let me know

**Comment by chadwhitacre** [comment]
Lgtm, thanks @bzg! Welcome aboard Gratipay 2.0! :-)

**Comment by bzg** [comment]
Thanks! I'll wait a few weeks until I can rewrite some parts of http://orgmode.org/worg/ then announce this on the orgmode mailing list.  Hopefully people will join the team and Gratipay.
