### ISSUE TITLE
Byebug

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#45]
https://gratipay.com/byebug/

@deivid-rodriguez, your team application is being reviewed here.

**Comment by deivid-rodriguez** [comment]
Thanks!

**Comment by chadwhitacre** [comment]
Lgtm. Welcome aboard, @deivid-rodriguez! :-)

**Comment by deivid-rodriguez** [comment]
Thanks and congrats for the new gratipay!

**Comment by chadwhitacre** [comment]
Thanks! :-)
