### ISSUE TITLE
juice-shop

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#47]
https://gratipay.com/juice-shop/

@bkimminich, your team application is being reviewed here.  It will be open for one week.

**Comment by chadwhitacre** [comment]
Looks great, @bkimminich. I'd love to see your Team on Gratipay. If there are no objections raised in the next week I'll be happy to approve it! :-)

**Comment by chadwhitacre** [comment]
Approved! Welcome aboard, @bkimminich! :-)
