### ISSUE TITLE
KoNLPy

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#48]
https://gratipay.com/konlpy/

@e9t, your team application is being reviewed here.  It will be open for one week.

**Comment by chadwhitacre** [comment]
Looks awesome, @e9t, thanks for applying! I'll be happy to approve this if there are no objections raised by others in the next week. :-)

**Comment by chadwhitacre** [comment]
Approved! Welcome aboard, @e9t! :dancer:
