### ISSUE TITLE
Bootsnipp

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#49]
https://gratipay.com/bootsnipp/

@msurguy, your team application is being reviewed here.  It will remain open for a week.

**Comment by chadwhitacre** [comment]
Thanks for the application, @msurguy. The onboarding and to-do links for [your Team](https://gratipay.com/bootsnipp/) point to your Twitter account. We're looking for something a little more substantial than that in both cases. Is Bootsnipp open-source?

**Comment by msurguy** [comment]
@whit537 Bootsnipp is not open source but the snippets on the site are (over 500 of them), Up until now the community would ask if they could help in some way and I would contact them via email to talk about specific items that they could do. I will create a WIKI on Github and some more details on how the users could help.

**Comment by chadwhitacre** [comment]
Any news on the onboarding wiki?

**Comment by msurguy** [comment]
@whit537 you can close this issue and remove Bootsnipp request as I don't own the site anymore. Thanks!

**Comment by chadwhitacre** [comment]
Sounds good. Congrats on the sale! :-)
