### ISSUE TITLE
Git Galaxy

### ISSUE THREAD

**Issue by mattbk** [gratipay/team-review#50]
https://gratipay.com/git-galaxy/

@Cyruxx, your team application is being reviewed here.  It will remain open for a week.

**Comment by w3z315** [comment]
Cool, thanks!

**Comment by chadwhitacre** [comment]
Thanks for the application, @Cyruxx! The onboarding and to-do links point to http://git-galaxy.com/, and not to onboarding documentation or a task list. We're looking for something more substantial in both cases. Is Git Galaxy open-source?

**Comment by chadwhitacre** [comment]
Ping @Cyruxx.

**Comment by w3z315** [comment]
You're right, that's missing. I didn't know that this is just for open
source projects.
Am 18.09.2015 01:25 schrieb "Chad Whitacre" notifications@github.com:

**Comment by mattbk** [comment]
It doesn't have to be open source, but the work itself needs to be open, so generally open-source projects have an easy way to do this.

**Comment by chadwhitacre** [comment]
Closing for now, @Cyruxx. Feel free to reapply if you decide to offer open work! :-)
