### ISSUE TITLE
Pylons Project

### ISSUE THREAD

**Issue by digitalresistor** [gratipay/team-review#51]
I created a new team for the Pylons Project:

https://gratipay.com/pylons/

@mmerickel, @mcdonc and myself were already on Gratipay.

Cheers,
Bert

**Comment by rohitpaulk** [comment]
[!m](http://motivate.im/) @bertjwregeer

**Comment by chadwhitacre** [comment]
Thanks for the application @bertjwregeer! Approved! :dancer: 

That said and done, do you mind if I change the to-do URL to [this GitHub search](https://github.com/search?q=user%3APylons&type=Issues&utf8=%E2%9C%93)?

Also, who all's tips should we migrate to the new Pylons Team? Yourself @mmerickel @mcdonc? Who else?

**Comment by digitalresistor** [comment]
I am not sure who else on the Pylons team has current tips. Also, I don't mind if you change the URL to that :-).

**Comment by chadwhitacre** [comment]
@bertjwregeer Okay, I'll migrate your tips today, and give @mmerickel @mcdonc a couple days to chime in ...

> Also, I don't mind if you change the URL to that :-).

Done! :-)

**Comment by mcdonc** [comment]
@whit537 yes, please migrate me to this project too.  Many thanks!  You're doing good stuff!

**Comment by mmerickel** [comment]
Yeah migrate me as well. Thank you.

**Comment by chadwhitacre** [comment]
Will do for next week! Yinz rock!

Anyone else that should have their tips migrated to Pylons, just send them here. Thanks! :-)

**Comment by stevepiercy** [comment]
@bertjwregeer @mcdonc @mmerickel Names are important. The Team name "Pylons" is ambiguous and could mean either "Pylons Web Framework" or "Pylons Project". Could we please make the Team name "PylonsProject" to be consistent with the marketing and branding efforts?

@whit537 would there be any technical issue that would prevent a renaming?

Sorry to pee in your cornflakes, everyone. This is pretty big deal to me and a few other folks working on marketing and branding of the Pylons Project and its projects. Thanks for your consideration.

**Comment by stevepiercy** [comment]
@whit537 I am the Team Owner for https://gratipay.com/knopproject/ I already migrated my personal tips to KnopProject. Would it be possible to migrate again a portion of those tips, leaving say 25¢ in KnopProject? I want to promote both projects, and showing some income instead of $0.00 might attract more contributors to KnopProject. Please let me know. Thank you!

**Comment by digitalresistor** [comment]
Sorry @stevepiercy! Didn't think much about the name when I created the team.

**Comment by chadwhitacre** [comment]
> Could we please make the Team name "PylonsProject" to be consistent with the marketing and branding efforts?

Done: https://gratipay.com/pylonsproject/. :)

> Would it be possible to migrate again a portion of those tips, leaving say 25¢ in KnopProject?

Sorry, we need to not get into splitting up tips, especially already-migrated ones, because it would get too messy. I think the answer here is to go drum up some new payments from KnopProject and PylonsProject users! :-)

**Comment by chadwhitacre** [comment]
Also, do you have a better logo? The one I grabbed from the website ended up kinda small:

https://gratipay.com/pylonsproject/

**Comment by stevepiercy** [comment]
@whit537 Thank you for the name change!

> Sorry, we need to not get into splitting up tips, especially already-migrated ones, because it would get too messy. I think the answer here is to go drum up some new payments from KnopProject and PylonsProject users! :-)

No worries. More users is part of my plan for world domination. :smiling_imp: 

> Also, do you have a better logo.

Why, yes, we do! Here's our full-size avatar on GitHub.
![Pylons Project logo](https://avatars2.githubusercontent.com/u/452227)

**Comment by chadwhitacre** [comment]
> Here's our full-size avatar on GitHub.

Thanks, updated!

https://gratipay.com/pylonsproject/

**Comment by stevepiercy** [comment]
@whit537 Thank you! And thank you @bertjwregeer for taking on the responsibility to make this happen!

**Comment by chadwhitacre** [comment]
I failed to migrate additional payments this week. I'm sorry. :-(

**Comment by chadwhitacre** [comment]
I'm looking at converting tips for @mcdonc @mmerickel into payments to PylonsProject.

**Comment by chadwhitacre** [comment]
Alright, here's the script I'm using (adapted from [`migrate_tips`](https://github.com/gratipay/gratipay.com/blob/1916/gratipay/models/team.py#L147-L181)):

``` sql
INSERT INTO payment_instructions
            (ctime, mtime, participant, team, amount, is_funded)
     SELECT ct.ctime
          , ct.mtime
          , ct.tipper
          , 'pylonsproject'
          , ct.amount
          , ct.is_funded
       FROM current_tips ct
       JOIN participants p ON p.username = tipper
      WHERE ct.tippee in ('mcdonc', 'mmerickel')
        AND p.claimed_time IS NOT NULL
        AND p.is_suspicious IS NOT TRUE
        AND p.is_closed IS NOT TRUE
```

I've tested it on a backup.

**Comment by chadwhitacre** [comment]
Done.

**Comment by chadwhitacre** [comment]
:dancer:

**Comment by digitalresistor** [comment]
How do people assign part of the tips to themselves?

**Comment by bertjwregeer** [comment]
How do people split the tips the project gets?

**Comment by bertjwregeer** [comment]
How do people split tips?

**Comment by chadwhitacre** [comment]
@bertjwregeer It's a long story (and I believe that @stevepiercy has been following along), but we haven't brought that back yet. We're trying to be careful not to trip people up with unexpected tax responsibilities, etc. You can find more under https://github.com/gratipay/gratipay.com/issues/3433.

**Comment by digitalresistor** [comment]
Okay, so I am going to have to send the money to the various people involved...

**Comment by chadwhitacre** [comment]
Yes.
