### ISSUE TITLE
survivejs

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/team-review#52]
https://gratipay.com/survivejs/

Originally approved under https://github.com/gratipay/inside.gratipay.com/issues/234, then rejected because of [FD2750](https://gratipay.freshdesk.com/helpdesk/tickets/2750):

> I realized asking for donations is illegal in Finland... Would it be possible for you to drop my team[?]

---

> The quickest way for me to turn off your Team was to "reject" it, so that's what I've done. Once we implement [Team closing](https://github.com/gratipay/gratipay.com/issues/3602) we'll re-approve it and you [can] close it out. You're on the list over on that ticket, so we will notify you when Team closing is ready.

**Comment by mattbk** [comment]
Team officially closed. Interesting discussion in FD about the rules in Finland and how people are able to collect donations. For example, OpenCollective works, but Gratipay does not.

**Comment by mattbk** [comment]
> Do you have any links about the legality of donations in Finland? We'd like to know more, in case this comes up again.

> https://en.wikipedia.org/wiki/Money_Collection_Act might be a starting point. In short, you would need a permit and the government is fairly strict about it. Certain causes are fine.
> My current understanding is that I can work around this very problem with Open Collective as they'll collect the money while I invoice them through my company. Some Finnish companies have done this sort of proxy arrangements to get on Kickstarter.
> I know this is a niche case for you so I wouldn't put too much thought on it. Our legislation has weird parts like this.
