### ISSUE TITLE
The Perl Review

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/team-review#53]
https://gratipay.com/the-perl-review/

@briandfoy, your team application is being reviewed here. It will remain open for a week.

**Comment by chadwhitacre** [comment]
Thanks for the application, @briandfoy! :-)

I'm having trouble seeing how I as an individual would get involved in your work, because the onboarding and to-do URLs you provided link to your GitHub profile, and not to onboarding documentation or a task list per se. Would you say that you're intending to offer "[open work](https://gratipay.com/about/)"? I see some hints in this direction such as https://github.com/briandfoy/PerlPowerTools/issues/7. Can we find better links for onboarding and to-do that would communicate this?

**Comment by briandfoy** [comment]
I don't understand your trouble seeing how you'd get involved. Clone a repo, do work, and that's it. There's no complicated process and no requirements on who can participate.

You've already approved exactly my situation with CPAN-BOOK https://gratipay.com/cpan-book/ .

**Comment by chadwhitacre** [comment]
You're right that we've handled this situation inconsistently. Sorry. You're welcome to join us on #82 to discuss the general case.

**Comment by chadwhitacre** [comment]
Circling back here after #82.

Seem like https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+user%3Abriandfoy makes sense as the to-do URL.

How about we use https://github.com/gratipay/team-review/issues/53#issuecomment-145047795 as the onboarding URL? :-)

You good with that, @briandfoy?

**Comment by chadwhitacre** [comment]
Hearing no objections ... welcome aboard! :-)
