### ISSUE TITLE
The Coinsultants

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/team-review#54]
https://gratipay.com/the-coinsultants/

@nerdfiles, your team application is being reviewed here. It will remain open for a week.

**Comment by chadwhitacre** [comment]
Thanks for the application, @nerdfiles.

It doesn't look to me like the Coinsultants is a good fit for Gratipay, because the Coinsultants is an "exclusive club" capped to 300 members, with an initiation fee and yearly membership dues (per the [to-do](https://thecoinsultants.com/the-basics/) link). This sounds to me like the opposite of [open work](https://gratipay.com/about/)!

Anyone else seeing differently?

**Comment by chadwhitacre** [comment]
Hearing no objections ...

**Comment by chadwhitacre** [comment]
I've whitelisted the ~user for a 1.0 payout.

**Comment by nerdfiles** [comment]
Thank you. Makes sense. Appreciate the review.

**Comment by nerdfiles** [comment]
May we take down the page altogether?

**Comment by chadwhitacre** [comment]
I'd prefer not to, because seeing which Teams we reject is valuable information for folks considering applying themselves. Is the issue that your Gratipay page shows up on a Google search for "coinsultants"? If that's the issue, would it suffice for us to add a `noindex` meta tag to rejected profiles? (I've reticketed that as https://github.com/gratipay/gratipay.com/issues/3846, because I think it's a good idea regardless of what we decide to do here.)
