### ISSUE TITLE
ContribKanban.com

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/team-review#64]
@gratipay-gremlin dropped the ball on this one:

https://gratipay.com/contribkanban-com/

**Comment by chadwhitacre** [comment]
@mglaman Thanks for the Gratipay Team application [for ContribKanban.com](https://gratipay.com/contribkanban-com/)! :dancer: 

Sorry, our little gremlin dropped the ball and we're just kicking off a review ticket now ...

**Comment by chadwhitacre** [comment]
I've manually fixed up the `review_url`.

**Comment by chadwhitacre** [comment]
Rest of the links look good, application approved! :-)

@mglaman Looks like the logo file also got dropped (or you got around it?). Do you have a logo file we could upload for you?

**Comment by mglaman** [comment]
I'll get something together - there isn't much of a logo. Will write better
contributing docs, too!

**Comment by chadwhitacre** [comment]
@mglaman Any closer to a logo? :-)

**Comment by mglaman** [comment]
@whit537 I'm trying to take a stab at a logo in Inkscape, just a lot of things going on at the moment ( newborn (: )

**Comment by chadwhitacre** [comment]
Ah, congrats! :dancer: 

No worries. :-)

**Comment by mattbk** [comment]
Status: Approved, still open for details.

**Comment by chadwhitacre** [comment]
I hacked together a logo and posted it.

```
[gratipay] $ heroku config -s -a gratipay | run_dammit /dev/stdin -c ~/personal/gratipay/gratipay.com/env/bin/python load-images.py contribkanban-com
Processing contribkanban-com ...done.
[gratipay] $ cd ~/personal/gratipay/gratipay.com/
[gratipay] $ git diff
diff --git a/gratipay/billing/payday.py b/gratipay/billing/payday.py
index 77bdb58..d2e6935 100644
--- a/gratipay/billing/payday.py
+++ b/gratipay/billing/payday.py
@@ -26,8 +26,6 @@ from gratipay.models import check_db
 from psycopg2 import IntegrityError


-with open('sql/payday.sql') as f:
-    PAYDAY = f.read()


 class ExceptionWrapped(Exception): pass
```

If you want a different one let us know, @mglaman! :-)
