### ISSUE TITLE
Team Jacinth

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/team-review#8]
https://gratipay.com/team-jacinth/

**Comment by chadwhitacre** [comment]
Nope. Off-[brand](http://inside.gratipay.com/big-picture/brand/).

![1021790_jacinth_gratipay](https://cloud.githubusercontent.com/assets/134455/8601032/665d5228-2637-11e5-923b-0cd7f53c7c22.png)

**Comment by chadwhitacre** [comment]
That's from https://inkbunny.net/submissionview.php?id=756692.

**Comment by mattbk** [comment]
Team owner has replied with comments at https://gratipay.freshdesk.com/helpdesk/tickets/2645 (login required).

**Comment by mattbk** [comment]
Team owner comments for additional consideration as we go forward (posted with permission):

> Thank you for the reply. Now that I know where to look, I can point at the fact that it was referenced here https://github.com/gratipay/applications/issues/8#ref-pullrequest-89449418 that a response had never been sent to me. Obviously I hoped for a different response. Before your transition to "Gratipay 2.0" I enjoyed the ability to receive crowdfunded revenue for creative works in a model other than Patreon, but it seems that your new mission does not support generation of creative content.
> 
> My team review was rejected due to being off-brand. I do not dispute that the sort of work I do is not in line with the picture Gratipay is painting of themselves. However, the document referenced as a basis for this, http://inside.gratipay.com/big-picture/brand/ really does not back up this statement.
> 
> The Gratipay brand is listed in the ultra-vague terms of being pro - gratitude, generosity, love, honesty, kindness, collaboration, openness, direct interpersonal communication, discussion, deliberation, and safety, and anti - conflict, combativeness, divisiveness, intimidation, and outrage. I would strongly urge that, if this document is going to be used as a basis to approve or deny applicants, it should be worded in more concrete, less general terms. I assure you that, as a revenue-seeker and author, I am not anti-love, anti-kindness, or pro-outrage. 
> 
> I hope that you consider my comments thoughtfully and seriously, the way they were intended. I appreciate your consideration and I am disappointed I will not be able to do further business with you.
> 
> Thanks,
> Heather Turing.
