### ISSUE TITLE
How to change logo?

### ISSUE THREAD

**Issue by duythien** [gratipay/team-review#84]
Hi team,

My team https://gratipay.com/phanbook/  have  just active and I want to change logo, but I'm does not see options. Can you help me change logo

**Comment by chadwhitacre** [comment]
@duythien It's manual right now until we land https://github.com/gratipay/gratipay.com/issues/3545. I've added a +1 for you over there.

In the mean time, want to post an image here and I will take care of it for you? :-)

Should be square, we'll crop it if not, and then resize it to 160x160 and 48x48 using http://gip.rocks/.

**Comment by duythien** [comment]
@whit537 

Nice, I just ask feature this, right now I have not the logo to change, I will contact you when I have a logo

**Comment by chadwhitacre** [comment]
Okay, sounds good! :-)

**Comment by chadwhitacre** [comment]
Closing for now, @duythien. Feel free to reopen when you have a logo ready. :-)

**Comment by mattbk** [comment]
@duythien You can now edit your Team on the Team page.
